# Check out the main file, included with an 'include' statement a couple of
# lines below. Or simply type 'make' at your prompt.
verbose:                     # If first, becomes default target 
include ../Programs/Makefile # If first, make's default target is 'help'
final:                       # If first, becomes default target.
